### ISSUE TITLE
Move into JuliaGraphs?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/MetaGraphsNext.jl#1]
If you transfer this into JuliaGraphs I'll add you as a maintainer.

**Comment by bramtayl** [comment]
I tried that and I got the message "You don’t have the permission to create public repositories on JuliaGraphs"

**Comment by sbromberger** [comment]
Huh. I think you have to transfer ownership. I'll accept and then add you as the maintainer.

**Comment by bramtayl** [comment]
Ok, I transferred it to you

**Comment by sbromberger** [comment]
Oops. You transferred it to me, personally, instead of JuliaGraphs. I'll just re-transfer. Give it a few minutes.

**Comment by sbromberger** [comment]
You should have some invitations to accept. (Make sure you're using 2-factor auth on your github account.) Once you accept the invitations, you should be the (only) maintainer of the repo under JuliaGraphs. You're in charge of inviting any other collaborators!

**Comment by bramtayl** [comment]
Yay!

**Comment by bramtayl** [comment]
@sbromberger maybe we should make an announcement?

**Comment by sbromberger** [comment]
Oh, absolutely. Did you create an initial release? I'll be happy to help you draft something if you want.

**Comment by bramtayl** [comment]
That would be great! I'm not even sure what an initial release is supposed to be, to be honest. I could register the package?

**Comment by sbromberger** [comment]
Yeah, in short, the steps are
1) make sure your `Project.toml` is correct, and set the initial version (I'd suggest `v0.1.0`)
1) use [Registrator](https://github.com/JuliaRegistries/Registrator.jl ) to register the package
2) wait 3 days
3) when it's registered, tag (in github) v0.1.0 and use github to create a release based on the tag
4) announce on discourse.

**Comment by bramtayl** [comment]
Ok, well here's a start. @JuliaRegistrator register

**Comment by bramtayl** [comment]
@sbromberger I keep getting distracted. Ok, so I think I have tagbot installed as a github action but it doesn't seem to be working. So I manually tagged and pushed. There seems to be a release 0.1.0 on github now? So ready to announce?

**Comment by sbromberger** [comment]
Yes!!! Nice work. Time to announce!
