### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/MetaGraphsNext.jl#18]
Maybe this is a slightly longer-term issue, but I'd like to have this package available in the General registry. In particular, this would make it usable in Pluto notebooks.

**Comment by gdalle** [comment]
@bramtayl any thoughts on this?

**Comment by bramtayl** [comment]
Hmm, I thought I had registered it. Looks like it's in the registry? https://github.com/JuliaRegistries/General/tree/master/M/MetaGraphsNext

**Comment by gdalle** [comment]
Oh well sorry @bramtayl, since there were no installation instructions with `Pkg.add` in the README I though it wasn't in General yet.

**Comment by bramtayl** [comment]
Np
