### ISSUE TITLE
Throw a BoundsError when setting an attribute for a vertex that doesn't exist

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaGraphs/MetaGraphsNext.jl#2]
The current behavior is that `g[:a] = "hello"` sets the vertex attribute for vertex `:a` to `"hello"` *and* it creates a new vertex with the index `:a` if it doesn't exist already. This syntax looks convenient, but I think it's a bit dangerous. Normally in Julia if you try to set a value at an index that doesn't exist, you get a `BoundsError`. I think it would be best to stick with that convention here. So if you want to add a vertex you have to explicitly add it via `add_vertex!(g, :a, "hello")`.

**Comment by bramtayl** [comment]
I modeled this behavior on `Dict`, which does create new indexes.

**Comment by bramtayl** [comment]
Given that `Dict` does the same thing, I'm not too concerned, but feel free to reopen if you disagree.

**Comment by CameronBieganek** [comment]
One thing that I like about the `SimpleGraph`s API is that the data structure used to store the graph is abstracted away from the user. In other words, the user uses `add_vertex!` and `add_edge!` without any hint of how the graph is stored under the hood. But with the MetaGraphsNext API, it's pretty clear that the graph is stored as a dictionary.

Also, I find it a little weird that if I want to add a new vertex with no metadata, I have to do this:

```julia
g[:a] = nothing
```

**Comment by bramtayl** [comment]
I'm not a big fan of `g[:a] = nothing` either... I could just add a method

```
add_vertex!(g::MetaGraph, label) = add_vertex!(g, label, nothing)
```
?

**Comment by CameronBieganek** [comment]
> I could just add a method

Yeah, that seems reasonable.
