### ISSUE TITLE
Arrange based on vertex code instead of vertex metadata

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/MetaGraphsNext.jl#22]
Currently, the function `arrange` is useful to define a default order within the edges of undirected `MetaGraph`s. However, it compares the metadata of both vertices, which may fail if they are not comparable. I suggest comparing the vertex codes instead

**Comment by bramtayl** [comment]
Hm, I'm not exactly sure what you mean. The comparison I see [here](https://github.com/JuliaGraphs/MetaGraphsNext.jl/blob/e7d9761a9fb8c5a908a248d03f05f3a743921cdc/src/metaundigraph.jl#L13) compares codes, not labels.

**Comment by gdalle** [comment]
Ah yes, my bad, I had forgotten that both code and metadata were stored inside `vprops`. I changed this in my recent PR btw
