### ISSUE TITLE
Make the custom vertex index optional

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaGraphs/MetaGraphsNext.jl#3]
Currently one has to define a custom vertex index in order to use MetaGraphsNext. But I don't always need a custom vertex index. For example, suppose I want to use MetaGraphsNext to make a simple weighted graph. Here's what I would have to do:

```julia
julia> g = MetaGraph(Graph(), Label=Int, EdgeMeta=Float64)
Meta graph based on a {0, 0} undirected simple Int64 graph with vertices indexed by Int64(s), Nothing(s) vertex metadata, Float64(s) edge metadata, nothing as graph metadata, and default weight 1.0

julia> add_vertex!(g, 1, nothing)
true

julia> add_vertex!(g, 2, nothing)
true

julia> add_vertex!(g, 3, nothing)
true

julia> add_edge!(g, 1, 2, 0.3)
true

julia> add_edge!(g, 2, 3, 2.1)
true
```

Side note: Currently the only `add_vertex!` constructor is the `add_vertex!(g::MetaGraph, label, val)` constructor, hence the need for the third argument with `nothing` in it in the above example.

So far it looks like I've been using a normal integer index, but it's actually a custom index that *happens* to be equal to the underlying integer index:

```julia
julia> g.vprops
Dict{Int64,Tuple{Int64,Nothing}} with 3 entries:
  2 => (2, nothing)
  3 => (3, nothing)
  1 => (1, nothing)
```

Maybe that's ok, but it seems a little wasteful to me. It could also lead to bugs if the programmer thinks they are using the normal integer index. For example, the following should throw an error if the normal integer index is being used:

```julia
julia> g = MetaGraph(Graph(), Label=Int, EdgeMeta=Float64)
Meta graph based on a {0, 0} undirected simple Int64 graph with vertices indexed by Int64(s), Nothing(s) vertex metadata, Float64(s) edge metadata, nothing as graph metadata, and default weight 1.0

julia> add_vertex!(g, 1, nothing)
true

julia> add_vertex!(g, 3, nothing)
true
```

But it doesn't throw an error because it is actually creating a custom index:

```julia
julia> g.vprops
Dict{Int64,Tuple{Int64,Nothing}} with 2 entries:
  3 => (2, nothing)
  1 => (1, nothing)
```

**Comment by bramtayl** [comment]
I agree this is potentially confusing. The reason I decided to require labels is because vertex codes get reassigned after `rem_vertex!`. That makes relying on them a little dangerous.

**Comment by bramtayl** [comment]
As a minimal step, I could add a warning to the docstring saying that using `Int`s as Labels could cause confusion. Another option could be disallowing `Int`s as Labels, which might dovetail nicely with your suggestion here: https://github.com/JuliaGraphs/MetaGraphsNext.jl/issues/4#issue-614512266

**Comment by bramtayl** [comment]
`MetaGraphs` currently have a mish-mash of features: graph level meta data, vertex level metadata, edge metadata, edge weights, and vertex labels. I did think about a way for users to pick and choose the features they want, but decided it would make the code-base too complex. But I'd be open to ideas on this front.

**Comment by bramtayl** [comment]
Hopefully the clarification in https://github.com/JuliaGraphs/MetaGraphsNext.jl/commit/e65a1bf439c8c2d1c131808515a9baebbf6ecb48 should help. Feel free to reopen if not.
