### ISSUE TITLE
Type stability tests

### ISSUE THREAD

**Issue by mroavi** [JuliaGraphs/MetaGraphsNext.jl#30]
The promise of this package is that it is type-stable. However, there are no tests that check this. I think that this type of test is of upmost importance for this package.

**Comment by bramtayl** [comment]
These would be great!

**Comment by gdalle** [comment]
@mroavi I completely agree, do you want to try it?

**Comment by mroavi** [comment]
Hey @gdalle . I'm super booked at the moment. I'll let you know once I can free up some time to contribute to this package though.
