### ISSUE TITLE
MetaGraphs.jl vs MetaGraphsNext.jl performance benchmark

### ISSUE THREAD

**Issue by mroavi** [JuliaGraphs/MetaGraphsNext.jl#31]
A performance benchmark comparison between MetaGraphs.jl and MetaGraphsNext.jl would be very valuable. It would basically justify the existence of this package (and a potential replacement for MetaGraphs.jl). The question it would answer would be: how much performance improvement can we achieve by implementing a type-stable version of MetaGraphs.jl? The answer would help a lot of people answering another question: Is the performance improvement worth migrating? I think the answer is yes.

**Comment by bramtayl** [comment]
This would be great!

**Comment by hdavid16** [comment]
What is the roadmap for graphs with metadata in Julia? I'm happy to contribute in this and have been using MetaGraphs.jl a lot. I haven't used MetaGraphsNext.jl but I like the interface after glancing at it.  Is MetaGraphsNext.jl just experimental?

**Comment by mroavi** [comment]
Take a look at this issue: https://github.com/JuliaGraphs/Graphs.jl/issues/35
I believe that there is consent with regards to the fact that https://github.com/JuliaGraphs/MetaGraphs.jl can be improved.
This package and https://github.com/gdalle/MetaDataGraphs.jl are efforts to do so.
It would be nice if we could unite our efforts to work together towards a common objective: a better MetaGraphs.jl.

**Comment by hdavid16** [comment]
Found it: https://github.com/JuliaGraphs/Graphs.jl/issues/128

**Comment by bramtayl** [comment]
That sounds good! This package started out as a PR against MetaGraphs, but after the changes became too breaking, the previous MetaGraphs maintainer suggested splitting off into a new package.

**Comment by gdalle** [comment]
Hey @mroavi, do you have any suggestion of benchmarking task we could use? I was thinking shortest paths with edge weights and maybe vertex attributes telling us whether we can use a given vertex or not
