### ISSUE TITLE
Is `default_weight` really necessary?

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/MetaGraphsNext.jl#46]
At the moment, edge weights are computed with `weight_function`, and `default_weight` is only used when the edge does not exist. Shouldn't we rather throw an error?

**Comment by bramtayl** [comment]
I mean, I think if we want `MetaWeights` to be an abstract matrix, we have to return something for every combination of two vertices, I think?

**Comment by gdalle** [comment]
Good point
