### ISSUE TITLE
Allow getproperty and setproperty! syntax for vertex labels

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaGraphs/MetaGraphsNext.jl#5]
It would be cool if the following syntax were supported:

```julia
g[:a].color = "blue"

g[:a, :b].size = 2
```

**Comment by bramtayl** [comment]
This might be nice. I think I would like to maintain the consistency with the `Dict` interface. If this goes through in Base, I would absolutely be on board https://github.com/JuliaLang/julia/issues/25750

**Comment by bramtayl** [comment]
Then again, if JuliaLang/julia#25750 goes through, this will happen automatically. What would be nice to have though is getproperty and setproperty for vertex labels, so I'm renaming the issue. Let me know if you disagree.

**Comment by CameronBieganek** [comment]
> Then again, if [JuliaLang/julia#25750](https://github.com/JuliaLang/julia/issues/25750) goes through, this will happen automatically.

That's technically a breaking change, so it probably won't go through until 2.0. See [here](https://github.com/JuliaLang/julia/issues/25750#issuecomment-626348640).

**Comment by gdalle** [comment]
Closing since we won't do it unless Julia does it
