### ISSUE TITLE
Add constructors that infer the metadata types from the data values provided to constructor

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaGraphs/MetaGraphsNext.jl#6]
The current `MetaGraph` constructor requires the user to explicitly specify the types of the metadata via the arguments `Label`, `VertexMeta`, and `EdgeMeta`. That seems a little unusual to me. It's much more common for constructors to determine the values of type parameters based on the data passed to the constructor, e.g.

```julia
julia> [1, 2]
2-element Array{Int64,1}:
 1
 2

julia> ["hello", "world"]
2-element Array{String,1}:
 "hello"
 "world"
```

It would be nice if there were some constructors like the following that infer the type parameters from the data:

```julia
MetaGraph(
    SimpleGraph(),
    vertices = [(:a, :color => "blue"), (:b, :color => "red")],
    edges = [(:a, :b, :linewidth => 2)]
)
```

The fallback for creating a typed but empty graph would be something like the following:

```julia
MetaGraph{SimpleGraph{Int}, Symbol, Dict{Symbol, String}, Dict{Symbol, Int}}()
```

which corresponds to how one normally creates a typed but empty object. E.g., for a typed but empty dictionary, you would use this:

```julia
Dict{Symbol, String}()
```

Or for a typed but empty vector:

```julia
Vector{Int}()
```

...although for arrays we have the sugar `Int[]`.

**Comment by bramtayl** [comment]
This is a great idea!

**Comment by gdalle** [comment]
We don't have lots of constructors yet, but this seems like the next logical steps! Thanks for the idea

**Comment by gdalle** [comment]
@CameronBieganek following up on this, do you want to draw up a PR?

**Comment by gdalle** [comment]
Side note: this is actually essential for our type stability claim, cause the constructor with types as kwargs is not inferrable
