### ISSUE TITLE
More compact REPL representation of MetaGraphs

### ISSUE THREAD

**Issue by huguesmp** [JuliaGraphs/MetaGraphsNext.jl#63]
MetaGraphs print the underlying graph to the REPL when created, which can be very long for large graphs.

A more compact reprensentation would be useful for larger MetaGraphs.

Example:

![image](https://github.com/JuliaGraphs/MetaGraphsNext.jl/assets/71036729/3e446a46-4047-46e5-8e1d-d28acd9a1e4f)

**Comment by huguesmp** [comment]
I made a PR (#64) to try to improve this.

![image](https://github.com/JuliaGraphs/MetaGraphsNext.jl/assets/71036729/0787b3af-ab55-4821-803b-8b4df7beb863)

**Comment by gdalle** [comment]
Solved by #64
