### ISSUE TITLE
add_edge!(g, u, v) deletes existing edges if called twice with the same arguments

### ISSUE THREAD

**Issue by degregat** [JuliaGraphs/MetaGraphsNext.jl#70]
`add_edge!(g, u, v)` [from here](https://github.com/JuliaGraphs/MetaGraphsNext.jl/blob/5eb369b473fd50c665dec95cb0c9c5b591aa68de/src/graphs.jl#L178), when called with the same `u`, `v` twice, adds the edge the first time, deletes it the second time (and does not add it in subsequent calls), since the length of `g.graph` [does not change](https://github.com/JuliaGraphs/MetaGraphsNext.jl/blob/5eb369b473fd50c665dec95cb0c9c5b591aa68de/src/graphs.jl#L187).

## Example
```julia
using Graphs
using MetaGraphsNext

dg = MetaGraph(
    DiGraph();
    label_type = String,
    vertex_data_type = String,
)

add_vertex!(dg, "u", "foo")
add_vertex!(dg, "v", "bar")
add_edge!(dg, "u", "v")
println(length(dg.edge_data)) # == 1
add_edge!(dg, "u", "v")
println(length(dg.edge_data)) # == 0

g = MetaGraph(
    Graph();
    label_type = String,
    vertex_data_type = String,
)

add_vertex!(g, "u", "foo")
add_vertex!(g, "v", "bar")
add_edge!(g, "u", "v")
println(length(dg.edge_data)) # == 1 
add_edge!(g, "u", "v")
println(length(dg.edge_data)) # == 0
```

## Workaround
```julia
# For directed graphs
if !haskey(g.edge_data, (u, v))
  add_edge!(g, u, v)
end

# For undirected graphs
if !haskey(g.edge_data, (u, v)) && !haskey(g.edge_data, (v, u))
  add_edge!(g, u, v)
end
```

## Proposed Fix

Remove [this call](https://github.com/JuliaGraphs/MetaGraphsNext.jl/blob/5eb369b473fd50c665dec95cb0c9c5b591aa68de/src/graphs.jl#L188C9-L188C9) of `delete!` and only `return false`. If that does not lead to the expected behavior, add checks as described in the workaround inside `add_edge!`, s.t. users don't have to do that.

**Comment by bramtayl** [comment]
I think the only reason the `delete!` was there was in case adding the edge failed for another reason, e.g. the graph ran out of room or something. In which case, we should only delete if the edge doesn't exist. So we could change [this line](https://github.com/JuliaGraphs/MetaGraphsNext.jl/blob/5eb369b473fd50c665dec95cb0c9c5b591aa68de/src/graphs.jl#L179) to `!has_edge(meta_graph.graph, code_1, code_2)`?

**Comment by cecileane** [comment]
I discovered that too, and will add a fix to a PR very soon.
