### ISSUE TITLE
add all_neighbor_labels function

### ISSUE THREAD

**Issue by apriljunge** [JuliaGraphs/MetaGraphsNext.jl#76]
In _Graphs.jl_ the `all_neighbors` function returns in- and outneighbors for all graphs. This is especially needed for directed graphs. ([Docs](https://juliagraphs.org/Graphs.jl/dev/first_steps/access/#Vertex-properties)).

I think it would be nice to have a corresponding function like `all_neighbor_labels` in this package. Implementation should be straight forward [like in Graphs.jl](https://github.com/JuliaGraphs/Graphs.jl/blob/d1081b02c2a2d50ac0e4e95b1f84f17259b719d5/src/core.jl#L287-L290).

What do you think?

**Comment by gdalle** [comment]
I think we already do: https://juliagraphs.org/MetaGraphsNext.jl/dev/api/#MetaGraphsNext.neighbor_labels-Tuple{MetaGraph,%20Any}

**Comment by apriljunge** [comment]
This only works für undirected Graphs. For directed graphs `neighbor_labels` just returns labels of out neighbors. This is expected behaviour, because it relies on `Graphs.neighbors`. From the [docomentation of Graphs.jl for Graphs.neighbors](https://juliagraphs.org/Graphs.jl/dev/core_functions/core/#Graphs.neighbors-Tuple{AbstractGraph,%20Integer}):

> For directed graphs, the default is equivalent to [outneighbors](https://juliagraphs.org/Graphs.jl/dev/core_functions/interface/#Graphs.outneighbors-Tuple{Any,%20Any}); use [all_neighbors](https://juliagraphs.org/Graphs.jl/dev/core_functions/core/#Graphs.all_neighbors) to list inbound and outbound neighbors.

This is why I think `all_neighbor_labels` is still needed to get in- _and_ outbound neighbors on directed graphs.

**Comment by gdalle** [comment]
Oh right, sorry I missed that. Feel free to open a PR adding it then!

**Comment by gdalle** [comment]
Closed by #77
